import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';
export default function CompanyPage(){
 const {slug}=useParams(); const [company,setCompany]=useState<any>(null); const [page,setPage]=useState<any>(null); const [posts,setPosts]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:c}=await supabase.from('companies').select('*').eq('slug',slug).eq('status','ACTIVE').eq('public_page_enabled',true).maybeSingle(); if(!c){setLoading(false);return} setCompany(c); const [p,ps]=await Promise.all([supabase.from('company_pages').select('*').eq('company_id',c.id).eq('published',true).maybeSingle(),supabase.from('company_posts').select('*').eq('company_id',c.id).eq('published',true).order('published_at',{ascending:false})]); setPage(p.data);setPosts(ps.data||[]);setLoading(false)})()},[slug]);
 if(loading)return <div className="min-h-screen grid place-items-center">Loading company…</div>;
 if(!company)return <div className="min-h-screen grid place-items-center p-5"><div className="text-center"><h1 className="text-3xl font-black">Company not found</h1><Link to="/" className="text-[#f35a02] inline-block mt-4">← Back to ASOMAC</Link></div></div>;
 return <div className="min-h-screen bg-slate-50"><header style={{background:company.primary_color}} className="text-white"><div className="max-w-6xl mx-auto px-5 py-5 flex justify-between"><Link to="/" className="font-bold">ASSOMAC</Link><Link to="/" className="text-sm">All companies</Link></div><div className="max-w-6xl mx-auto px-5 py-20"><p className="uppercase tracking-widest text-sm opacity-80">ASOMAC MEMBER</p><h1 className="text-5xl font-black mt-3">{company.name}</h1><p className="text-xl mt-4 max-w-2xl opacity-90">{page?.tagline||company.description||'Welcome to our company page.'}</p></div></header><main className="max-w-6xl mx-auto px-5 py-12"><div className="grid lg:grid-cols-3 gap-8"><section className="lg:col-span-2"><h2 className="text-2xl font-black text-[#00194C]">About</h2><p className="text-slate-600 mt-4 whitespace-pre-wrap">{page?.about_text||company.description||'Company information will appear here.'}</p><h2 className="text-2xl font-black text-[#00194C] mt-12">Latest activities</h2><div className="grid gap-5 mt-5">{posts.map(p=><article className="card p-6" key={p.id}><span className="text-xs font-bold uppercase text-[#f35a02]">{p.post_type}</span><h3 className="text-xl font-bold mt-2">{p.title}</h3>{p.excerpt&&<p className="text-slate-500 mt-2">{p.excerpt}</p>}{p.body&&<p className="text-slate-600 mt-4 whitespace-pre-wrap">{p.body}</p>}</article>)}{!posts.length&&<div className="card p-6 text-slate-500">No public activities have been published yet.</div>}</div></section><aside className="card p-6 h-fit"><h3 className="font-bold">Contact</h3><div className="mt-4 space-y-3 text-sm text-slate-600"><p>{page?.contact_address||company.location||'Address not published'}</p><p>{page?.contact_phone||'Phone not published'}</p><p>{page?.contact_email||'Email not published'}</p></div></aside></div></main></div>
}