create extension if not exists pgcrypto;

create type public.user_scope as enum ('ASSOMAC','COMPANY','BRANCH','OWN_ACCOUNT');
create type public.person_kind as enum ('FIELD_OPERATIVE','BRANCH_MANAGER','STORE_MANAGER','SECRETARY','GROUND_MANAGER','FINANCE_MANAGER','BRANCH_DIRECTOR','COMPANY_DIRECTOR','STAFF');
create type public.record_status as enum ('ACTIVE','INACTIVE','SUSPENDED','CLOSED');

create table public.companies(id uuid primary key default gen_random_uuid(),name text not null unique,registration_number text unique,status record_status not null default 'ACTIVE',description text,logo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.branches(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),name text not null,address text,location text,phone text,email text,status record_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,name));
create table public.roles(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,scope user_scope not null,description text);
create table public.permissions(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text);
create table public.role_permissions(role_id uuid references public.roles(id) on delete cascade,permission_id uuid references public.permissions(id) on delete cascade,primary key(role_id,permission_id));
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,phone text,email text,status record_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_roles(user_id uuid references public.profiles(id) on delete cascade,role_id uuid references public.roles(id),company_id uuid references public.companies(id),branch_id uuid references public.branches(id),assigned_at timestamptz not null default now(),ended_at timestamptz,primary key(user_id,role_id,company_id,branch_id));
create table public.people(id uuid primary key default gen_random_uuid(),profile_id uuid references public.profiles(id),kind person_kind not null,person_code text unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.person_assignments(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.people(id),company_id uuid not null references public.companies(id),branch_id uuid not null references public.branches(id),role_id uuid references public.roles(id),rank_code text,starts_at date not null,ends_at date,reason text,source text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),check(ends_at is null or ends_at>=starts_at));
create index person_assignments_person_idx on public.person_assignments(person_id,starts_at desc);
create index person_assignments_branch_idx on public.person_assignments(branch_id,starts_at,ends_at);
create table public.transfers(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.people(id),from_company_id uuid references public.companies(id),from_branch_id uuid references public.branches(id),to_company_id uuid not null references public.companies(id),to_branch_id uuid not null references public.branches(id),from_role_id uuid references public.roles(id),to_role_id uuid references public.roles(id),from_rank text,to_rank text,effective_date date not null,reason text,approval_status text not null default 'APPROVED',historical boolean not null default false,source text,notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create index transfers_person_idx on public.transfers(person_id,effective_date desc);
create table public.historical_entries(id uuid primary key default gen_random_uuid(),record_type text not null,person_name text,original_event_date date,company_name text,branch_name text,notes text,source_reference text,entered_by uuid references auth.users(id),entered_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id),action text not null,entity_type text,entity_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create table public.import_batches(id uuid primary key default gen_random_uuid(),file_name text,source_type text,scope_company_id uuid references public.companies(id),scope_branch_id uuid references public.branches(id),status text not null default 'STAGED',rows_processed integer not null default 0,rows_imported integer not null default 0,rows_skipped integer not null default 0,rows_failed integer not null default 0,created_by uuid references auth.users(id),created_at timestamptz not null default now(),completed_at timestamptz);
create table public.import_rows(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.import_batches(id) on delete cascade,row_number integer not null,raw_data jsonb not null,mapped_data jsonb,validation_errors jsonb,validation_status text not null default 'PENDING',created_at timestamptz not null default now(),unique(batch_id,row_number));

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=auth.uid() and r.code='ASSOMAC_ADMIN' and ur.ended_at is null); $$;
create or replace function public.has_permission(p text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from user_roles ur join role_permissions rp on rp.role_id=ur.role_id join permissions pe on pe.id=rp.permission_id where ur.user_id=auth.uid() and pe.code=p and ur.ended_at is null); $$;
create or replace function public.has_branch_access(b uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin() or exists(select 1 from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=auth.uid() and ur.branch_id=b and ur.ended_at is null and r.code in ('BRANCH_DIRECTOR','BRANCH_MANAGER','STORE_MANAGER','SECRETARY','GROUND_MANAGER','FINANCE_MANAGER')); $$;
create or replace function public.has_company_access(c uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin() or exists(select 1 from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=auth.uid() and ur.company_id=c and ur.ended_at is null and r.code in ('COMPANY_DIRECTOR')); $$;

alter table public.companies enable row level security; alter table public.branches enable row level security; alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.people enable row level security; alter table public.person_assignments enable row level security; alter table public.transfers enable row level security; alter table public.historical_entries enable row level security; alter table public.audit_logs enable row level security; alter table public.import_batches enable row level security; alter table public.import_rows enable row level security;

create policy companies_read on public.companies for select using (public.is_admin() or public.has_company_access(id));
create policy branches_read on public.branches for select using (public.is_admin() or public.has_company_access(company_id) or public.has_branch_access(id));
create policy profiles_self on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy user_roles_admin on public.user_roles for all using (public.is_admin() or user_id=auth.uid()) with check (public.is_admin());
create policy people_read on public.people for select using (public.is_admin() or exists(select 1 from person_assignments pa where pa.person_id=people.id and public.has_branch_access(pa.branch_id)));
create policy assignments_read on public.person_assignments for select using (public.is_admin() or public.has_branch_access(branch_id));
create policy transfers_read on public.transfers for select using (public.is_admin() or public.has_branch_access(to_branch_id) or (from_branch_id is not null and public.has_branch_access(from_branch_id)) or public.has_company_access(to_company_id) or (from_company_id is not null and public.has_company_access(from_company_id)));
create policy historical_admin on public.historical_entries for all using (public.is_admin()) with check (public.is_admin());
create policy audit_admin on public.audit_logs for select using (public.is_admin());
create policy import_admin on public.import_batches for all using (public.is_admin()) with check (public.is_admin());
create policy import_rows_admin on public.import_rows for all using (public.is_admin()) with check (public.is_admin());

insert into public.roles(code,name,scope,description) values
('ASSOMAC_ADMIN','ASSOMAC Administrator','ASSOMAC','Governance administration'),('COMPANY_DIRECTOR','Company Director','COMPANY','Company governance; no branch operations'),('BRANCH_DIRECTOR','Branch Director','BRANCH','Branch oversight and operations'),('BRANCH_MANAGER','Branch Manager','BRANCH','Day-to-day branch management'),('STORE_MANAGER','Store Manager','BRANCH','Stock and consignments'),('SECRETARY','Secretary','BRANCH','Recruitment and office'),('GROUND_MANAGER','Ground Manager','BRANCH','Daily expenses and ground operations'),('FINANCE_MANAGER','Finance Manager','BRANCH','Operative withdrawals and finance'),('FIELD_OPERATIVE','Field Operative','OWN_ACCOUNT','Own account and assigned operational records');
insert into public.permissions(code,name) values
('company.view','View companies'),('company.create','Create companies'),('company.update','Update companies'),('branch.view','View branches'),('branch.create','Create branches'),('branch.update','Update branches'),('people.view','View people'),('people.recruit','Recruit people'),('people.transfer','Transfer people'),('training.view','View training'),('training.manage','Manage training'),('rank.view','View ranks'),('rank.assign','Assign ranks'),('stock.view','View stock'),('stock.manage','Manage stock'),('consignment.view','View consignments'),('consignment.create','Create consignments'),('sales.view','View sales'),('sales.submit','Submit sales'),('sales.verify','Verify sales'),('commission.view','View commission'),('withdrawal.view','View withdrawals'),('withdrawal.request','Request withdrawal'),('withdrawal.approve','Approve withdrawal'),('expense.view','View expenses'),('expense.create','Create expense'),('expense.approve','Approve expense'),('complaint.view','View complaints'),('complaint.create','Create complaint'),('notification.view','View notifications'),('notification.create','Create notifications'),('audit.view','View audit logs'),('qr.scan','Scan consignment QR'),('analytics.view','View analytics'),('history.view','View history'),('history.manage','Manage historical entry'),('import.manage','Manage data migration');
